<?php
	// WARNING -- Please do not view before you solve the problems on your own, you are cheating yourself out of
	// a good learning experience.

	// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
	// will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
	/**
	 * Finds the sum of all the numbers divisible by 3 or 5 under a specified number
	 * @param  Number1    $number1  The first number of the sequence.
	 * @param  Number2    $number2  The second number of the sequence.
	 * @param  Max    	  $max  The upper bound number.
	 * @return Status
	 */ 
	function question2($number1, $number2, $max) {	
		$sum = 0;

		if ($number1 % 2 == 0) {
			$sum = $sum + $number1;
			
		} 

		while ($number2 < $max) {

			if ($number2 % 2 == 0) { 
				$sum = $sum + $number2;
				
			}

			echo $number2;

			$previous = $number1;
			$number1 = $number2;
			$number2 = $number2 + $previous;
		}

		echo "the sum of all even numbers in the Fibonacci sequence under " . $max ." is " . $sum;

	}

	question2(1,2,4000000);

?>